version: '3.8'

services:
  data-loader:
    build: ./data-loader
    command: "python3 load.py"
    ports:
      - 8080:8080 
    env_file: 
      - .env
    volumes:
      - ./:/workspace

  db-mysql:
    container_name: media-service-mysql
    image: mysql:5.7
    ports:
      - 3308:3306
    env_file:
      - .env
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./:/workspace

  media-service-s3:
    container_name: media-service-s3
    image: minio/minio:RELEASE.2022-05-19T18-20-59Z.fips
    ports:
      - 9000:80
      - 9001:9001
    env_file:
      - .env
    volumes:
      - ./:/workspace
    command: server /data --console-address ":9001" --address :80
